sonar.projectKey=ApiBR_vagas-aggregator-ui
sonar.organization=apibr
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.ts,src/**/*.test.tsx
sonar.exclusions=src/test/**,src/App.js,src/vite-env.d.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
