name: Build & Deploy via ftp

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      fullSemVer: ${{ steps.gitversion.outputs.fullSemVer }}

    steps:
    
    - name: Checkout repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
          fetch-depth: 0 

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0
      with:
        versionSpec: '6.x'

    - name: Determine Version
      id: gitversion
      uses: gittools/actions/gitversion/execute@7417b1089e2c7de93510f1901d656ddf60bb024f # v4.7.0

    - name: Set up Node.js 22
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
      with:
        node-version: 22.x

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    # - name: Test
    #   run: npm test

    - name: Upload build
      uses: sebastianpopp/ftp-action@ca3f8d253d20ddd6aa658f8cb27fc847fd610882 # releases/v2
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "dist/"
        remoteDir: "/public_html/ui/vagas/"
        options: "--delete"

  create_release:
    name: Create release
    needs: build
    runs-on: ubuntu-latest
    env:
      fullSemVer: ${{ needs.build.outputs.fullSemVer }}
      
    steps:
      - name: Create Release
        uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
        with:
          skipIfReleaseExists: true
          allowUpdates: false
          draft: false
          makeLatest: true
          tag: v${{ env.fullSemVer }}
          name: Release v${{ env.fullSemVer }}
          generateReleaseNotes: true
          body: Release ${{ env.fullSemVer }} of ${{ github.repository }}
