name: Sonar Cloud Analysis
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [opened, synchronize, reopened]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: npm install

      - name: Test and coverage
        run: npm run test -- --coverage --watchAll=false
          
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        if: >-
          (
            github.event_name == 'pull_request' &&
            github.event.pull_request.head.repo.full_name == github.repository
          ) || (
            github.event_name == 'pull_request_target' &&
            github.event.pull_request.head.repo.full_name != github.repository
          ) || (
            github.event_name == 'workflow_dispatch'
          )
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
